name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_version: [3.8]
        robot_version: [3, 4]

    steps:
    - uses: actions/checkout@v2

    - name: Setup mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Create the conda environment
      run: mamba install -q python=${{ matrix.python_version }} pip lunr flake8 pytest

    - name: Install robotframework
      run: mamba install -q robotframework=${{ matrix.robot_version }}

    - name: Install library
      run: pip install .

    - name: Flake8
      run: python -m flake8 robotframework_interpreter setup.py --ignore=E501,W504

    - name: Tests
      run: pytest tests
