name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_version: [3.8]
        robot_version: [3, 4]

    steps:
    - uses: actions/checkout@v2

    - name: Setup mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Create the conda environment
      shell: bash -l {0}
      run: mamba install -q python=${{ matrix.python_version }} pip lunr flake8 pytest

    - name: Install robotframework 3
      if: ${{ matrix.robot_version }} == 3
      shell: bash -l {0}
      run: mamba install -q robotframework=3

    - name: Install robotframework 4
      if: ${{ matrix.robot_version }} == 4
      shell: bash -l {0}
      run: pip install robotframework==4.0b1

    - name: Install library
      shell: bash -l {0}
      run: pip install .

    - name: Flake8
      shell: bash -l {0}
      run: |
        python -m flake8 robotframework_interpreter setup.py --ignore=E501,W504

    - name: Tests
      shell: bash -l {0}
      run: |
        pytest tests
